Migrate upstart changes
:Release Notes:
Migrate upstart changes

:Detailed Notes:
Remove wpa-supplicant, sleepd service files

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-68060]

Change-Id: If910d65b7f93dcb21de5e5fcf008261b91c4e0ae
Reviewed-on: http://gpro.lgsvl.com/220823
Reviewed-by: Eunmin Lim <eunmin.lim@lge.com>
Tested-by: Eunmin Lim <eunmin.lim@lge.com>
Reviewed-by: Sukil Hong <sukil.hong@lge.com>
Reviewed-on: http://gpro.lge.com/249594
Reviewed-by: OSE Helper Bot <ose@ci.lgsvl.net>
Reviewed-by: Sangwoo Kang <sangwoo82.kang@lge.com>

diff --git a/files/systemd/scripts/configurator-activity.sh.in b/files/systemd/scripts/configurator-activity.sh.in
--- a/files/systemd/scripts/configurator-activity.sh.in
+++ b/files/systemd/scripts/configurator-activity.sh.in
@@ -1,4 +1,5 @@
-# Copyright (c) 2017-2018 LG Electronics, Inc.
+#!/bin/sh
+# Copyright (c) 2018 LG Electronics, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -14,17 +15,17 @@
 #
 # SPDX-License-Identifier: Apache-2.0
 
-# A Client for Wi-Fi Protected Access (WPA)
+SEND_CNT=0
 
-[Unit]
-Description=webos - "%n"
-Requires=ls-hubd.service
-After=ls-hubd.service
-
-[Service]
-Type=simple
-OOMScoreAdjust=-500
-EnvironmentFile=-/var/systemd/system/env/wpa-supplicant.env
-ExecStartPre=/etc/systemd/system/scripts/wpa-supplicant.sh
-ExecStart=/usr/sbin/wpa_supplicant -u -s
-Restart=on-failure
+while [ $SEND_CNT -le 5 ]
+do
+    RES=`/usr/bin/luna-send -n 1 palm://com.palm.configurator/run '{"types":["activities"]}' | grep -q 'Message status unknown' && echo NG || echo OK` || true
+    if [ "$RES" != "OK" ]; then
+        logger -s "Configuring activities asynchronously - error, retrying"
+        usleep 500000
+        SEND_CNT=$((SEND_CNT + 1))
+    else
+        logger -s "Configuring activities asynchronously - successful"
+        SEND_CNT=6
+    fi
+done
